// Nameplates animados (pacote local em public/nameplates/).
// id -> [rotulo, arquivo]. Gerado a partir dos nomes dos arquivos.
export const NAMEPLATES = [
  ["2035", "2035", "2035.webm"],
  ["algeria", "Algeria", "algeria.webm"],
  ["andys_room_clouds", "Andy's Room Clouds", "andy's_room_clouds.webm"],
  ["angels", "Angels", "angels.webm"],
  ["aquarius", "Aquarius", "aquarius.webm"],
  ["argentina", "Argentina", "argentina.webm"],
  ["aries", "Aries", "aries.webm"],
  ["aurora", "Aurora", "aurora.webm"],
  ["australia", "Australia", "australia.webm"],
  ["austria", "Austria", "austria.webm"],
  ["autumn_breeze", "Autumn Breeze", "autumn_breeze.webm"],
  ["badtz_maru", "Badtz Maru", "badtz_maru.webm"],
  ["banana_bliss", "Banana Bliss", "banana_bliss.webm"],
  ["bb_8", "Bb 8", "bb_8.webm"],
  ["belgium", "Belgium", "belgium.webm"],
  ["berry_bunny", "Berry Bunny", "berry_bunny.webm"],
  ["black_mana", "Black Mana", "black_mana.webm"],
  ["bloomling", "Bloomling", "bloomling.webm"],
  ["blossoming_branch", "Blossoming Branch", "blossoming_branch.webm"],
  ["blue_mana", "Blue Mana", "blue_mana.webm"],
  ["bonsai", "Bonsai", "bonsai.webm"],
  ["bosnia_herzegovina", "Bosnia & Herzegovina", "bosnia_&_herzegovina.webm"],
  ["brazil", "Brazil", "brazil.webm"],
  ["busy_bee", "Busy Bee", "busy_bee.webm"],
  ["buzz_lightyear", "Buzz Lightyear", "buzz_lightyear.webm"],
  ["bye_bye", "Bye Bye", "bye_bye.webm"],
  ["camerica_caribbean", "C.america & Caribbean", "c.america_&_caribbean.webm"],
  ["camo_master", "Camo Master", "camo_master.webm"],
  ["canada", "Canada", "canada.webm"],
  ["cancer", "Cancer", "cancer.webm"],
  ["capricorn", "Capricorn", "capricorn.webm"],
  ["carbo_verde", "Carbo Verde", "carbo_verde.webm"],
  ["cat_beans", "Cat Beans", "cat_beans.webm"],
  ["cherry_blossoms", "Cherry Blossoms", "cherry_blossoms.webm"],
  ["cherry_surprise", "Cherry Surprise", "cherry_surprise.webm"],
  ["chococat", "Chococat", "chococat.webm"],
  ["cinnamoroll", "Cinnamoroll", "cinnamoroll.webm"],
  ["cityscape", "Cityscape", "cityscape.webm"],
  ["clappy_feet_base", "Clappy Feet (base)", "clappy_feet_(base).webm"],
  ["clappy_feet_dark", "Clappy Feet (dark)", "clappy_feet_(dark).webm"],
  ["clappy_feet_light", "Clappy Feet (light)", "clappy_feet_(light).webm"],
  ["clappy_feet_medium", "Clappy Feet (medium)", "clappy_feet_(medium).webm"],
  ["claptrap", "Claptrap", "claptrap.webm"],
  ["cloud_nine", "Cloud Nine", "cloud_nine.webm"],
  ["colombia", "Colombia", "colombia.webm"],
  ["cosmic_guardian", "Cosmic Guardian", "cosmic_guardian.webm"],
  ["cosmic_storm", "Cosmic Storm", "cosmic_storm.webm"],
  ["cosmic_twilight_flow_amethyst", "Cosmic Twilight Flow (amethyst)", "cosmic_twilight_flow_(amethyst).webm"],
  ["cosmic_twilight_flow_beryl", "Cosmic Twilight Flow (beryl)", "cosmic_twilight_flow_(beryl).webm"],
  ["cote_dlvoire", "Cote D'lvoire", "cote_d'lvoire.webm"],
  ["cozy_cat", "Cozy Cat", "cozy_cat.webm"],
  ["crimson_stallion", "Crimson Stallion", "crimson_stallion.webm"],
  ["croatia", "Croatia", "croatia.webm"],
  ["curacao", "Curacao", "curacao.webm"],
  ["cutesy_bow", "Cutesy Bow", "cutesy_bow.webm"],
  ["czechia", "Czechia", "czechia.webm"],
  ["d20_roll", "D20 Roll", "d20_roll.webm"],
  ["daisy_dream_bubbles", "Daisy Dream Bubbles", "daisy_dream_bubbles.webm"],
  ["dark_roses", "Dark Roses", "dark_roses.webm"],
  ["darth_vader", "Darth Vader", "darth_vader.webm"],
  ["donlad_splish_splash", "Donlad Splish Splash", "donlad_splish_splash.webm"],
  ["dr_congo", "Dr Congo", "dr_congo.webm"],
  ["dragon_ball", "Dragon Ball", "dragon_ball.webm"],
  ["dream_waves", "Dream Waves", "dream_waves.webm"],
  ["east_asia_oceania", "East Asia & Oceania", "east_asia_&_oceania.webm"],
  ["ecuador", "Ecuador", "ecuador.webm"],
  ["egypt", "Egypt", "egypt.webm"],
  ["elysian_tides", "Elysian Tides", "elysian_tides.webm"],
  ["encom_grid", "Encom Grid", "encom_grid.webm"],
  ["encore_orange", "Encore! (orange)", "encore!_(orange).webm"],
  ["encore_teal", "Encore! (teal)", "encore!_(teal).webm"],
  ["england", "England", "england.webm"],
  ["fairies", "Fairies", "fairies.webm"],
  ["falling_stars", "Falling Stars", "falling_stars.webm"],
  ["firefly_meadow", "Firefly Meadow", "firefly_meadow.webm"],
  ["fluttering_static", "Fluttering Static", "fluttering_static.webm"],
  ["france", "France", "france.webm"],
  ["gemini", "Gemini", "gemini.webm"],
  ["germany", "Germany", "germany.webm"],
  ["ghana", "Ghana", "ghana.webm"],
  ["glitch", "Glitch", "glitch.webm"],
  ["glowies", "Glowies", "glowies.webm"],
  ["go_sports", "Go Sports!", "go_sports!.webm"],
  ["gomah", "Gomah", "gomah.webm"],
  ["goofy_happy_tune", "Goofy Happy Tune", "goofy_happy_tune.webm"],
  ["gothic_arches", "Gothic Arches", "gothic_arches.webm"],
  ["green_mana", "Green Mana", "green_mana.webm"],
  ["grogu", "Grogu", "grogu.webm"],
  ["gudetama", "Gudetama", "gudetama.webm"],
  ["haiti", "Haiti", "haiti.webm"],
  ["hearts_reflection", "Heart's Reflection", "heart's_reflection.webm"],
  ["hello_kitty", "Hello Kitty", "hello_kitty.webm"],
  ["hermits_lantern", "Hermit's Lantern", "hermit's_lantern.webm"],
  ["hoppy_bois_perch", "Hoppy Boi's Perch", "hoppy_boi's_perch.webm"],
  ["hot_dog", "Hot Dog", "hot_dog.webm"],
  ["hunny_bunnies", "Hunny Bunnies", "hunny_bunnies.webm"],
  ["hyperspace", "Hyperspace", "hyperspace.webm"],
  ["ichi_nyan", "Ichi Nyan", "ichi_nyan.webm"],
  ["infinite_swirl", "Infinite Swirl", "infinite_swirl.webm"],
  ["iran", "Iran", "iran.webm"],
  ["iraq", "Iraq", "iraq.webm"],
  ["japan", "Japan", "japan.webm"],
  ["jordan", "Jordan", "jordan.webm"],
  ["k_heart_base", "K Heart (base)", "k_heart_(base).webm"],
  ["k_heart_dark", "K Heart (dark)", "k_heart_(dark).webm"],
  ["k_heart_light", "K Heart (light)", "k_heart_(light).webm"],
  ["k_heart_medium", "K Heart (medium)", "k_heart_(medium).webm"],
  ["koi_pond", "Koi Pond", "koi_pond.webm"],
  ["kuromi_x_my_melody", "Kuromi X My Melody", "kuromi_x_my_melody.webm"],
  ["ladybug_lulau", "Ladybug Lulau", "ladybug_lulau.webm"],
  ["leo", "Leo", "leo.webm"],
  ["libra", "Libra", "libra.webm"],
  ["light_wall_blue", "Light Wall (blue)", "light_wall_(blue).webm"],
  ["light_wall_red", "Light Wall (red)", "light_wall_(red).webm"],
  ["lil_inchy", "Lil' Inchy", "lil'_inchy.webm"],
  ["lil_stinker", "Lil Stinker", "lil_stinker.webm"],
  ["lone_wolf", "Lone Wolf", "lone_wolf.webm"],
  ["lotus_laterns", "Lotus Laterns", "lotus_laterns.webm"],
  ["love_meter", "Love Meter", "love_meter.webm"],
  ["lucky_bunny", "Lucky Bunny", "lucky_bunny.webm"],
  ["lucky_clover", "Lucky Clover", "lucky_clover.webm"],
  ["luna_moth", "Luna Moth", "luna_moth.webm"],
  ["magic_hearts_blue", "Magic Hearts (blue)", "magic_hearts_(blue).webm"],
  ["magic_hearts_orange", "Magic Hearts (orange)", "magic_hearts_(orange).webm"],
  ["magic_mists", "Magic Mists", "magic_mists.webm"],
  ["mando", "Mando", "mando.webm"],
  ["mando_and_grogu", "Mando And Grogu", "mando_and_grogu.webm"],
  ["manifesting_magic", "Manifesting Magic", "manifesting_magic.webm"],
  ["mexico", "Mexico", "mexico.webm"],
  ["mickey_twinkle_star", "Mickey Twinkle Star", "mickey_twinkle_star.webm"],
  ["middle_east_casia", "Middle East & C.asia", "middle_east_&_c.asia.webm"],
  ["midnight_mantas", "Midnight Mantas", "midnight_mantas.webm"],
  ["mini_goku", "Mini Goku", "mini_goku.webm"],
  ["mini_true_love", "Mini True Love", "mini_true_love.webm"],
  ["mini_vegeta", "Mini Vegeta", "mini_vegeta.webm"],
  ["mischief_meter", "Mischief Meter", "mischief_meter.webm"],
  ["moon_bloom", "Moon Bloom", "moon_bloom.webm"],
  ["moon_essence", "Moon Essence", "moon_essence.webm"],
  ["moonlit_charm", "Moonlit Charm", "moonlit_charm.webm"],
  ["morocco", "Morocco", "morocco.webm"],
  ["netherlands", "Netherlands", "netherlands.webm"],
  ["nevermore", "Nevermore", "nevermore.webm"],
  ["new_zealand", "New Zealand", "new_zealand.webm"],
  ["north_east_europe", "North & East Europe", "north_&_east_europe.webm"],
  ["north_africa", "North Africa", "north_africa.webm"],
  ["north_america", "North America", "north_america.webm"],
  ["norway", "Norway", "norway.webm"],
  ["oasis", "Oasis", "oasis.webm"],
  ["owlbear_cub", "Owlbear Cub", "owlbear_cub.webm"],
  ["panama", "Panama", "panama.webm"],
  ["pandoran_seas_ilu", "Pandoran Seas (ilu)", "pandoran_seas_(ilu).webm"],
  ["pandoran_seas_squid", "Pandoran Seas (squid)", "pandoran_seas_(squid).webm"],
  ["paraguay", "Paraguay", "paraguay.webm"],
  ["petal_bloom", "Petal Bloom", "petal_bloom.webm"],
  ["pisces", "Pisces", "pisces.webm"],
  ["pitter_patter", "Pitter Patter", "pitter_patter.webm"],
  ["pixi_dust", "Pixi Dust", "pixi_dust.webm"],
  ["planet_rings", "Planet Rings", "planet_rings.webm"],
  ["pluto_playful_friend", "Pluto Playful Friend", "pluto_playful_friend.webm"],
  ["pochacco", "Pochacco", "pochacco.webm"],
  ["pompompurin", "Pompompurin", "pompompurin.webm"],
  ["portugal", "Portugal", "portugal.webm"],
  ["qatar", "Qatar", "qatar.webm"],
  ["red_dragon", "Red Dragon", "red_dragon.webm"],
  ["red_mana", "Red Mana", "red_mana.webm"],
  ["ripper_awakens", "Ripper Awakens", "ripper_awakens.webm"],
  ["roly_roly_blue", "Roly Roly (blue)", "roly_roly_(blue).webm"],
  ["roly_roly_orange", "Roly Roly (orange)", "roly_roly_(orange).webm"],
  ["roly_roly_pink", "Roly Roly (pink)", "roly_roly_(pink).webm"],
  ["ryomen_sukuna", "Ryomen Sukuna", "ryomen_sukuna.webm"],
  ["sagittarius", "Sagittarius", "sagittarius.webm"],
  ["satoru_gojo", "Satoru Gojo", "satoru_gojo.webm"],
  ["saudi_arabia", "Saudi Arabia", "saudi_arabia.webm"],
  ["scorpio", "Scorpio", "scorpio.webm"],
  ["scotland", "Scotland", "scotland.webm"],
  ["secrect_agent", "Secrect Agent", "secrect_agent.webm"],
  ["senegal", "Senegal", "senegal.webm"],
  ["shattered_veil", "Shattered Veil", "shattered_veil.webm"],
  ["skibidi_toilet", "Skibidi Toilet", "skibidi_toilet.webm"],
  ["south_africa", "South Africa", "south_africa.webm"],
  ["south_america", "South America", "south_america.webm"],
  ["south_korea", "South Korea", "south_korea.webm"],
  ["spain", "Spain", "spain.webm"],
  ["spider_man_logo", "Spider-man (logo)", "spider-man_(logo).webm"],
  ["spider_man_no_logo", "Spider-man (no Logo)", "spider-man_(no_logo).webm"],
  ["spider_man_vs_venom", "Spider-man Vs Venom", "spider-man_vs_venom.webm"],
  ["spirit_blossom_petrals", "Spirit Blossom Petrals", "spirit_blossom_petrals.webm"],
  ["spirit_blossom_springs", "Spirit Blossom Springs", "spirit_blossom_springs.webm"],
  ["spirit_moon", "Spirit Moon", "spirit_moon.webm"],
  ["spirit_of_spring", "Spirit Of Spring", "spirit_of_spring.webm"],
  ["spray_doodles", "Spray Doodles", "spray_doodles.webm"],
  ["sproutling", "Sproutling", "sproutling.webm"],
  ["squad_wipe", "Squad Wipe", "squad_wipe.webm"],
  ["star_drift", "Star Drift", "star_drift.webm"],
  ["star_struck", "Star Struck", "star_struck.webm"],
  ["starfall_tides", "Starfall Tides", "starfall_tides.webm"],
  ["starfall_tides_nightshade", "Starfall Tides (Nightshade)", "starfall_tides_(Nightshade).webm"],
  ["starfall_tides_rose", "Starfall Tides (rose)", "starfall_tides_(rose).webm"],
  ["starfall_tides_void", "Starfall Tides (void)", "starfall_tides_(void).webm"],
  ["starlight_whales", "Starlight Whales", "starlight_whales.webm"],
  ["sub_saharan_africa", "Sub Saharan Africa", "sub_saharan_africa.webm"],
  ["sun_and_moon", "Sun And Moon", "sun_and_moon.webm"],
  ["sunlit_radiance", "Sunlit Radiance", "sunlit_radiance.webm"],
  ["sweden", "Sweden", "sweden.webm"],
  ["sweetheart_charm", "Sweetheart Charm", "sweetheart_charm.webm"],
  ["switzerland", "Switzerland", "switzerland.webm"],
  ["sword_of_legend", "Sword Of Legend", "sword_of_legend.webm"],
  ["taurus", "Taurus", "taurus.webm"],
  ["the_clawww", "The Clawww", "the_clawww.webm"],
  ["the_grid_fireworks", "The Grid Fireworks", "the_grid_fireworks.webm"],
  ["the_same_duck", "The Same Duck", "the_same_duck.webm"],
  ["toasty", "Toasty", "toasty.webm"],
  ["touch_grass", "Touch Grass", "touch_grass.webm"],
  ["towers_strike", "Tower's Strike", "tower's_strike.webm"],
  ["tunisia", "Tunisia", "tunisia.webm"],
  ["turkey", "Turkey", "turkey.webm"],
  ["tv_woman", "Tv Woman", "tv_woman.webm"],
  ["twilight", "Twilight", "twilight.webm"],
  ["twilight_dusk", "Twilight (dusk)", "twilight_(dusk).webm"],
  ["twilight_fuchsia", "Twilight (fuchsia)", "twilight_(fuchsia).webm"],
  ["under_the_sea", "Under The Sea", "under_the_sea.webm"],
  ["united_states", "United States", "united_states.webm"],
  ["uruguay", "Uruguay", "uruguay.webm"],
  ["uzbekistan", "Uzbekistan", "uzbekistan.webm"],
  ["vault", "Vault", "vault.webm"],
  ["vengeance", "Vengeance", "vengeance.webm"],
  ["venom_logo", "Venom (logo)", "venom_(logo).webm"],
  ["venom_no_logo", "Venom (no Logo)", "venom_(no_logo).webm"],
  ["virgo", "Virgo", "virgo.webm"],
  ["western_europe", "Western Europe", "western_europe.webm"],
  ["white_mana", "White Mana", "white_mana.webm"],
  ["woodsprite", "Woodsprite", "woodsprite.webm"],
  ["woodys_badge", "Woody's Badge", "woody's_badge.webm"],
  ["yoda", "Yoda", "yoda.webm"],
  ["yuji_itadori", "Yuji Itadori", "yuji_itadori.webm"],
  ["yunaras_aion_erna", "Yunara's Aion Er'na", "yunara's_aion_er'na.webm"],
];
export const NAMEPLATE_IDS = new Set(NAMEPLATES.map(([id]) => id));
export const NAMEPLATE_FILES = Object.fromEntries(NAMEPLATES.map(([id, , file]) => [id, file]));
export const nameplateSrc = (id) => NAMEPLATE_FILES[id] ? `/nameplates/${encodeURI(NAMEPLATE_FILES[id])}` : null;
