import {test,expect} from "@playwright/test";
test.beforeEach(async({page})=>{
 const response=await page.request.post("/api/auth/login",{data:{username:"demo",password:"demo123"}});
 expect(response.ok()).toBeTruthy();await page.goto("/app");
 await expect(page.getByTitle("Configurações",{exact:true})).toBeVisible();
});
test("perfil salva avatar, banner e efeitos e fecha ao concluir",{tag:"@profile"},async({page})=>{
 const errors=[];page.on("pageerror",e=>errors.push(e.message));
 await page.getByTitle("Configurações",{exact:true}).click();
 await page.getByRole("button",{name:"Editar perfil e conta"}).click();
 const editor=page.getByRole("dialog",{name:"Editar perfil",exact:true});await expect(editor).toBeVisible();
 const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");
 await editor.locator('input[type=file]').nth(0).setInputFiles({name:"avatar.png",mimeType:"image/png",buffer:png});
 await editor.locator('input[type=file]').nth(1).setInputFiles({name:"banner.png",mimeType:"image/png",buffer:png});
 await editor.getByRole("button",{name:"Salvar alterações"}).click();
 await expect(editor).toBeHidden();
 await page.getByTitle("Configurações",{exact:true}).click();
 await page.getByRole("button",{name:"Editar perfil e conta"}).click();
 await expect(editor).toBeVisible();
 const me=await(await page.request.get("/api/auth/me")).json();
 expect(me.user.avatar).toMatch(/^\/api\/users\/.+\/media\/avatar\?v=/);expect(me.user.banner).toMatch(/^\/api\/users\/.+\/media\/banner\?v=/);
 await editor.getByRole("button",{name:"Efeitos e estilo",exact:true}).click();
 await editor.getByRole("button",{name:"Vagalumes",exact:true}).click();
 await editor.getByRole("button",{name:"Salvar alterações"}).click();
 await expect(editor).toBeHidden();
 await page.screenshot({path:"test-results/profile-studio.png",fullPage:true});
 expect(errors).toEqual([]);
});
test("aparência aplica uma imagem ao aplicativo inteiro",async({page})=>{
 await page.getByTitle("Configurações",{exact:true}).click();
 const settings=page.getByRole("dialog",{name:"Configurações",exact:true});
 await settings.getByRole("button",{name:"Aparência",exact:true}).click();
 const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");
 await settings.locator('input[type=file][accept*="image/png"]').setInputFiles({name:"app-background.png",mimeType:"image/png",buffer:png});
 await expect(settings.getByText("Preferência sincronizada na sua conta.",{exact:true})).toBeVisible();
 const shell=page.locator(".app-shell");
 await expect(shell).toHaveClass(/has-app-wallpaper/);
 await expect.poll(()=>shell.evaluate(element=>getComputedStyle(element).getPropertyValue("--app-wallpaper").trim())).toContain("url(");
 const mainBackground=await page.locator(".main-content").evaluate(element=>getComputedStyle(element).backgroundColor);
 expect(mainBackground).not.toBe("rgb(24, 25, 30)");
 await settings.getByRole("button",{name:"Remover fundo",exact:true}).click();
 await expect(shell).not.toHaveClass(/has-app-wallpaper/);
});
test("home mantém contraste e preenche o ícone do servidor",async({page})=>{
 const png="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
 const created=await(await page.request.post("/api/servers",{data:{name:"Ícone visual"}})).json();
 const updated=await page.request.patch(`/api/servers/${created.server.id}`,{data:{icon:png}});
 expect(updated.ok()).toBeTruthy();
 const appearance=await page.request.patch("/api/auth/me",{data:{preferences:{appSurfaceColor:"#111214",appAccentColor:"#a3ff12"}}});
 expect(appearance.ok()).toBeTruthy();
 await page.reload();
 const serverButton=page.locator('.server-icon[title="Ícone visual"]');
 await expect(serverButton).toBeVisible();
 const serverImage=serverButton.locator(".server-icon-img");
 await expect(serverImage).toBeVisible();
 expect(await serverImage.evaluate(element=>getComputedStyle(element).objectFit)).toBe("cover");
 await page.locator(".brand-home").click();
 const store=page.locator(".home-sidebar .home-nav").filter({hasText:"Loja"});
 await store.click();
 await expect(store).toHaveClass(/selected/);
 expect(await store.evaluate(element=>getComputedStyle(element).backgroundColor)).not.toBe("rgb(255, 255, 255)");
 await page.locator(".home-sidebar .home-nav").filter({hasText:"Amigos"}).click();
 const addFriend=page.getByRole("button",{name:"Adicionar amigo",exact:true});
 expect(await addFriend.evaluate(element=>getComputedStyle(element).color)).not.toBe("rgb(35, 165, 90)");
 await addFriend.click();
 await expect(addFriend).toHaveClass(/home-tab-selected/);
 expect(await addFriend.evaluate(element=>getComputedStyle(element).color)).toBe("rgb(242, 243, 245)");
 await page.screenshot({path:"test-results/home-visual-polish.png",fullPage:true});
 await page.request.patch("/api/auth/me",{data:{preferences:{appSurfaceColor:null,appAccentColor:null}}});
});
test("artes animadas carregam uma página leve por vez",async({page})=>{
 const me=await(await page.request.get("/api/auth/me")).json();
 expect((await page.request.post("/api/auth/login",{data:{username:"sesh_admin",password:"browser-admin-test-only"}})).ok()).toBeTruthy();
 expect((await page.request.patch(`/api/users/${me.user.id}/badges`,{data:{badges:["nitro_classic"]}})).ok()).toBeTruthy();
 expect((await page.request.post("/api/auth/login",{data:{username:"demo",password:"demo123"}})).ok()).toBeTruthy();
 await page.reload();
 await page.getByTitle("Configurações",{exact:true}).click();
 await page.getByRole("button",{name:"Editar perfil e conta"}).click();
 const editor=page.getByRole("dialog",{name:"Editar perfil",exact:true});
 await editor.getByRole("button",{name:"Artes animadas",exact:true}).click();
 const effects=editor.locator(".profile-art-settings").first();
 await expect(effects.locator(".profile-art-choice")).toHaveCount(6);
 await effects.getByRole("button",{name:"2",exact:true}).click();
 await expect(effects.locator(".profile-art-choice")).toHaveCount(6);
 const frames=editor.locator(".profile-art-settings").nth(1);
 await expect(frames.locator(".profile-frame-choice")).toHaveCount(8);
 await editor.getByRole("button",{name:"Jogos de interesse",exact:true}).click();
 await expect(editor.locator(".games-gallery>button")).toHaveCount(24);
 await editor.getByRole("button",{name:"Efeitos e estilo",exact:true}).click();
 await expect(editor.locator(".studio-grid-avatar-frame .studio-choice")).toHaveCount(18);
 await expect(editor.locator(".nameplate-grid .nameplate-choice")).toHaveCount(18);
 const plateChoice=editor.locator(".nameplate-choice").nth(1);
 await plateChoice.click();
 await expect(editor.locator(".profile-editor-preview .identity-nameplate-preview video")).toBeVisible();
 const framePager=editor.getByRole("navigation",{name:"Páginas de molduras"});
 await expect(framePager.locator(".pager-pages>button")).toHaveCount(7);
 const jump=framePager.getByLabel("Ir para página de molduras");
 await jump.selectOption({value:"3"});
 await expect(jump).toHaveValue("3");
 await expect(framePager.locator(".pager-current")).toHaveText("4");
});
test("cache de mensagens guarda somente conteúdo cifrado",async({page})=>{
 const created=await(await page.request.post("/api/servers",{data:{name:"Cache seguro"}})).json();
 const channel=created.server.channels.find(item=>item.type==="text");
 await page.goto(`/app?server=${created.server.id}&channel=${channel.id}`);
 await expect(page.locator(`.channel-row[data-channel-id="${channel.id}"]`)).toBeVisible();
 await expect.poll(()=>page.evaluate(()=>new Promise(resolve=>{const open=indexedDB.open("sesh-secure-message-cache");open.onerror=()=>resolve(0);open.onsuccess=()=>{const request=open.result.transaction("entries","readonly").objectStore("entries").count();request.onsuccess=()=>resolve(request.result);request.onerror=()=>resolve(0);};})),{timeout:10000}).toBeGreaterThan(0);
 const entries=await page.evaluate(()=>new Promise(resolve=>{const open=indexedDB.open("sesh-secure-message-cache");open.onsuccess=()=>{const request=open.result.transaction("entries","readonly").objectStore("entries").getAll();request.onsuccess=()=>resolve(request.result.map(entry=>({keys:Object.keys(entry),cipherBytes:entry.cipher?.byteLength||0,ivBytes:entry.iv?.byteLength||0})));};}));
 expect(entries.length).toBeGreaterThan(0);
 expect(entries.every(entry=>entry.cipherBytes>0&&entry.ivBytes===12&&!entry.keys.includes("messages"))).toBeTruthy();
});test("backend entrega animações em partes cacheáveis",async({page})=>{
 const response=await page.request.get("/nameplates/brazil.webm",{headers:{Range:"bytes=0-1023"}});
 expect(response.status()).toBe(206);
 expect(response.headers()["content-range"]).toMatch(/^bytes 0-1023\//);
 expect(response.headers()["accept-ranges"]).toBe("bytes");
 expect(response.headers()["cache-control"]).toContain("immutable");
 expect((await response.body()).byteLength).toBe(1024);
});
test("microfone mede áudio real e libera captura",async({page})=>{
 await page.getByTitle("Configurações",{exact:true}).click();
 await page.getByRole("button",{name:"Testar microfone",exact:true}).click();
 await expect(page.getByRole("button",{name:"Parar teste"})).toBeVisible();
 await expect.poll(async()=>Number(await page.getByRole("meter").getAttribute("aria-valuenow"))).toBeGreaterThan(0);
 await page.getByRole("button",{name:"Parar teste"}).click();
 await expect(page.getByRole("button",{name:"Testar microfone",exact:true})).toBeVisible();
 await expect(page.locator("audio[controls]")).toBeVisible();
 await page.screenshot({path:"test-results/microphone-settings.png",fullPage:true});
});
test("cargo criado permanece após salvar e reabrir",async({page})=>{
 const result=await(await page.request.post("/api/servers",{data:{name:"Comunidade de teste"}})).json();
 await page.reload();await page.getByTitle("Comunidade de teste",{exact:true}).click();
 await page.getByTitle("Configurações do servidor",{exact:true}).click();
 await page.getByRole("button",{name:"Cargos",exact:true}).click();
 await page.getByRole("button",{name:"Criar cargo",exact:true}).click();
 await page.getByLabel("Nome do cargo",{exact:true}).fill("Guardiões");
 await page.getByLabel("Efeito do cargo",{exact:true}).selectOption("dark_wave");
 await expect(page.locator(".role-style-sample")).toHaveClass(/role-style-dark_wave/);
 await page.getByRole("button",{name:"Salvar cargo",exact:true}).click();
 await expect(page.locator(".settings-role-item").filter({hasText:"Guardiões"})).toBeVisible();
 await page.getByLabel("Fechar configurações",{exact:true}).click();
 await page.getByTitle("Configurações do servidor",{exact:true}).click();
 await page.getByRole("button",{name:"Cargos",exact:true}).click();
 await expect(page.locator(".settings-role-item").filter({hasText:"Guardiões"})).toBeVisible();
 await page.getByRole("button",{name:"Membros",exact:true}).click();
 const ownerRow=page.locator('.server-role-member[data-member-id="'+result.server.ownerId+'"]');
 await expect(ownerRow).toBeVisible();
 await ownerRow.locator("select").selectOption({label:"Guardiões"});
 await page.getByRole("button",{name:"Salvar membros",exact:true}).click();
 await expect(page.getByText("Membros atualizados.",{exact:true})).toBeVisible();
 await page.getByLabel("Fechar configurações",{exact:true}).click();
 await expect(page.locator(".member-sidebar .member").first()).toHaveAttribute("data-member-id",result.server.ownerId);
 await expect(page.locator(".member-owner-group .member-role-group-title")).toContainText("Guardiões");
 await page.locator(".member-sidebar .member").first().click();
 const profileRole=page.locator(".member-profile-popover .profile-role-badge");
 await expect(profileRole).toBeVisible();
 await expect(profileRole).toContainText("Guardiões");
 await expect(profileRole).toHaveCSS("border-radius","999px");
 await profileRole.hover();
 await expect(profileRole).not.toHaveCSS("transform","none");
 await page.screenshot({path:"test-results/profile-role-harmony.png"});
 const server=await(await page.request.get("/api/servers/"+result.server.id)).json();
 expect(server.server.roles.some(role=>role.name==="Guardiões"&&role.style==="dark_wave")).toBeTruthy();
 expect(server.members.find(member=>member.id===result.server.ownerId).roleId).toBe(server.server.roles.find(role=>role.name==="Guardiões").id);
 await page.screenshot({path:"test-results/roles.png",fullPage:true});
});
test("placa lateral permanece animada no servidor",async({page,browser})=>{
 const me=(await(await page.request.get("/api/auth/me")).json()).user;
 const admin=await browser.newContext();
 try{
  await admin.request.post("http://127.0.0.1:34170/api/auth/login",{data:{username:"browser-admin@sesh.test",password:"browser-admin-test-only"}});
  expect((await admin.request.patch("http://127.0.0.1:34170/api/users/"+me.id+"/badges",{data:{badges:["nitro_classic"]}})).ok()).toBeTruthy();
  const updatedProfile=await page.request.patch("/api/auth/me",{data:{profilePlate:"brazil"}});
  expect(updatedProfile.ok()).toBeTruthy();
  expect((await updatedProfile.json()).user.profilePlate).toBe("brazil");
  const result=await(await page.request.post("/api/servers",{data:{name:"Comunidade placa hover"}})).json();
  const serverState=await(await page.request.get("/api/servers/"+result.server.id)).json();
  expect(serverState.members.find(member=>member.id===result.server.ownerId).profilePlate).toBe("brazil");
  const memberResponse=page.waitForResponse(response=>response.url().endsWith("/api/servers/"+result.server.id)&&response.request().method()==="GET");
  await page.goto("/app?server="+result.server.id);
  const renderedServer=await(await memberResponse).json();
  expect(renderedServer.members.find(member=>member.id===result.server.ownerId).profilePlate).toBe("brazil");
  await expect(page.getByTitle("Comunidade placa hover",{exact:true})).toBeVisible();
  const member=page.locator('.member-sidebar .member[data-member-id="'+result.server.ownerId+'"]');
  await expect(member).toBeVisible();
  await expect(member).toHaveAttribute("data-profile-plate","brazil");
  const video=member.locator(".member-nameplate-surface video");
  await expect(video).toBeVisible();
  await expect.poll(()=>video.evaluate(node=>!node.paused)).toBe(true);
  await page.locator(".channel-header").hover();
  await expect.poll(()=>video.evaluate(node=>!node.paused)).toBe(true);
 }finally{await admin.close();}
});
test("menu de menções mantém cada resultado em sua própria linha",async({page})=>{
 await page.request.post("/api/servers",{data:{name:"Comunidade menções"}});
 await page.reload();
 await page.getByTitle("Comunidade menções",{exact:true}).click();
 const composer=page.getByRole("textbox",{name:/Conversar em #/});
 await composer.fill("@");
 const options=page.locator(".mention-suggestion");
 await expect(options.first()).toBeVisible();
 const boxes=await options.evaluateAll(nodes=>nodes.map(node=>{const rect=node.getBoundingClientRect();return {top:rect.top,bottom:rect.bottom,height:rect.height};}));
 expect(boxes.length).toBeGreaterThanOrEqual(2);
 expect(boxes.every(box=>box.height>=46)).toBeTruthy();
 expect(boxes.slice(1).every((box,index)=>box.top>=boxes[index].bottom-1)).toBeTruthy();
});
test("emoji picker insere e envia mensagem",async({page})=>{
 await page.request.post("/api/servers",{data:{name:"Comunidade emoji"}});
 await page.reload();
 await expect(page.getByTitle("Configurações",{exact:true})).toBeVisible();
 await page.getByTitle("Comunidade emoji",{exact:true}).click();
 await page.getByRole("button",{name:"Escolher emoji"}).click();
 await expect(page.locator(".EmojiPickerReact")).toBeVisible();
 await expect(page.locator(".EmojiPickerReact img").first()).toBeVisible();
 await page.screenshot({path:"test-results/emoji-picker-modern.png",fullPage:true});
 await page.getByRole("button",{name:"rosto risonho",exact:true}).click();
 await expect(page.locator(".composer input:not([type=file])")).toHaveValue("😀");
 await page.locator(".send-button").click();
 await expect(page.locator('.emoji-message img[alt="😀"]')).toBeVisible();
});
