import React,{useMemo,useState} from "react";
import {Search,Users,X} from "lucide-react";

export default function CreateDirectGroupModal({friends,onClose,onCreate,Avatar}){
 const [name,setName]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState(()=>new Set()),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const visible=useMemo(()=>friends.filter(friend=>[friend.displayName,friend.username].some(value=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[friends,query]);
 const toggle=id=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else if(next.size<7)next.add(id);return next;});
 const submit=async event=>{event.preventDefault();if(selected.size<2||busy)return;setBusy(true);setError("");try{await onCreate({name:name.trim(),memberIds:[...selected]});onClose();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <div className="modal-backdrop" onClick={event=>event.target===event.currentTarget&&onClose()}><form className="direct-group-create" role="dialog" aria-modal="true" aria-label="Criar grupo de DM" onSubmit={submit}><header><div><span className="eyebrow">NOVA CONVERSA</span><h2>Criar grupo de DM</h2></div><button type="button" aria-label="Fechar" onClick={onClose}><X/></button></header><label className="setting-field">Nome do grupo <input value={name} maxLength={60} onChange={event=>setName(event.target.value)} placeholder="Ex.: Noite de jogos"/></label><label className="direct-group-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar amigos"/></label><div className="direct-group-create-list">{visible.map(friend=><label key={friend.id} className={selected.has(friend.id)?"selected":""}><Avatar user={friend} small/><span>{friend.displayName}<small>@{friend.username}</small></span><input type="checkbox" checked={selected.has(friend.id)} onChange={()=>toggle(friend.id)}/></label>)}</div>{error&&<p className="form-error">{error}</p>}<footer><span><Users size={15}/>{selected.size}/7 selecionados · mínimo 2</span><button className="prompt-confirm" disabled={selected.size<2||busy}>{busy?"Criando…":"Criar grupo"}</button></footer></form></div>;
}
