import React,{useEffect,useRef,useState} from "react";
import {Mic,MicOff,Paperclip,Phone,PhoneOff,Send,Users,X} from "lucide-react";
import {api} from "./api";
import AttachmentView from "./AttachmentView";
import EmojiPicker from "./EmojiPicker";
import EmojiText from "./EmojiText";
import {readAttachment} from "./files";
import useFileDrop from "./useFileDrop";
import {StyledName} from "./ProfileEditor";

const time=value=>new Date(value).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});

export default function GroupDirectMessages({group,currentUser,onClose,onStartPrivateCall,activePrivateCall,onLeaveVoice,onToggleMute,muted=false,voiceParticipants=[],Avatar}){
 const [messages,setMessages]=useState([]),[draft,setDraft]=useState(""),[attachment,setAttachment]=useState(null),[loading,setLoading]=useState(true),[reading,setReading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const fileInput=useRef(null),bottom=useRef(null),readEpoch=useRef(0);
 const drop=useFileDrop(files=>attachFiles(files));
 const merge=message=>setMessages(current=>{const pending=message.clientMessageId&&current.find(item=>item.sendState&&item.clientMessageId===message.clientMessageId);if(pending)return current.map(item=>item.id===pending.id?message:item);return current.some(item=>item.id===message.id)?current:[...current,message];});
 useEffect(()=>{let active=true;setLoading(true);setMessages([]);setError("");const receive=({detail})=>{if(detail.groupId===group.id)merge(detail.message);};window.addEventListener("sesh:direct-group-message",receive);api.directGroupMessages(group.id).then(result=>{if(active)setMessages(result.messages||[]);}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;readEpoch.current++;window.removeEventListener("sesh:direct-group-message",receive);};},[group.id]);
 useEffect(()=>{bottom.current?.scrollIntoView({block:"end"});},[messages.length]);
 useEffect(()=>{const key=event=>event.key==="Escape"&&onClose();window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[onClose]);
 async function attachFiles(files){if(!files.length)return;if(files.length>1)return setError("Envie um arquivo por mensagem.");const attempt=++readEpoch.current;setReading(true);setError("");try{const value=await readAttachment(files[0]);if(attempt===readEpoch.current)setAttachment(value);}catch(e){if(attempt===readEpoch.current)setError(e.message);}finally{if(attempt===readEpoch.current)setReading(false);}}
 async function send(event){event.preventDefault();if(reading||(!draft.trim()&&!attachment))return;const clientMessageId=crypto.randomUUID(),payload={content:draft.trim(),attachment,clientMessageId},optimistic={id:`pending:${clientMessageId}`,clientMessageId,groupId:group.id,authorId:currentUser.id,author:currentUser,content:payload.content,attachment:payload.attachment,createdAt:new Date().toISOString(),sendState:"sending",pendingPayload:payload};setDraft("");setAttachment(null);setError("");setMessages(current=>[...current,optimistic]);try{const result=await api.sendDirectGroupMessage(group.id,payload);merge(result.message);}catch(e){setError(e.message);setMessages(current=>current.map(item=>item.id===optimistic.id?{...item,sendState:"failed"}:item));}}
 async function startGroupCall(){if(busy)return;setBusy(true);setError("");try{await onStartPrivateCall(group.members.filter(member=>member.id!==currentUser.id).map(member=>member.id),group.id);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="direct-conversation group-direct-conversation"><header className="direct-header"><button className="icon-button" aria-label="Voltar para amigos" onClick={onClose}><X size={20}/></button><div className="group-dm-avatar"><Users size={20}/></div><div className="direct-header-person"><strong>{group.name}</strong><span>{group.members.length} membros</span></div><div className="direct-header-actions"><button disabled={busy} onClick={startGroupCall} title="Iniciar chamada do grupo"><Phone size={18}/></button></div></header>
 {activePrivateCall?.call?.groupId===group.id&&<div className="direct-call-strip"><div className="direct-call-people"><span className="direct-call-live"/><div><strong>{activePrivateCall.name}</strong><small>{voiceParticipants.length} conectado{voiceParticipants.length===1?"":"s"}</small></div></div><div className="direct-call-controls"><button onClick={onToggleMute}>{muted?<MicOff size={18}/>:<Mic size={18}/>}</button><button className="danger" onClick={onLeaveVoice}><PhoneOff size={18}/></button></div></div>}
 <div className={"direct-main file-drop-zone"+(drop.dragging?" dragging":"")} {...drop.bind}><div className="direct-messages" aria-live="polite"><div className="direct-welcome group-welcome"><div className="group-welcome-avatars">{group.members.slice(0,4).map(member=><Avatar key={member.id} user={member}/>)}</div><h2>{group.name}</h2><p>Este é o começo do grupo com {group.members.map(member=>member.displayName).join(", ")}.</p></div>{loading&&<p className="direct-loading">Carregando grupo…</p>}{messages.map(message=><article className={`dm-message${message.sendState?` message-${message.sendState}`:""}`} key={message.id}><Avatar user={message.author} small/><div><header><StyledName user={message.author}/><time>{time(message.createdAt)}</time></header><p><EmojiText text={message.content}/></p>{message.attachment&&<AttachmentView attachment={message.attachment} alt="Arquivo enviado no grupo"/>}{message.sendState==="sending"&&<span className="message-delivery-state">Enviando…</span>}{message.sendState==="failed"&&<span className="message-delivery-state">Falha no envio</span>}</div></article>)}<div ref={bottom}/></div>{error&&<p className="form-error" role="alert">{error}</p>}{attachment&&<div className="dm-attachment"><AttachmentView attachment={attachment} preview/><button onClick={()=>setAttachment(null)}>Remover</button></div>}<form className="direct-composer" onSubmit={send}><input ref={fileInput} type="file" hidden onChange={event=>{attachFiles(Array.from(event.target.files||[]));event.target.value="";}}/><button type="button" onClick={()=>fileInput.current?.click()} aria-label="Anexar arquivo"><Paperclip size={19}/></button><input maxLength={4000} value={draft} onChange={event=>setDraft(event.target.value)} placeholder={`Conversar em ${group.name}`}/><EmojiPicker onSelect={emoji=>setDraft(current=>current+emoji)}/><button disabled={reading||(!draft.trim()&&!attachment)} aria-label="Enviar mensagem"><Send size={20}/></button></form></div>
 <aside className="direct-profile group-profile"><div className="group-profile-icon"><Users size={30}/></div><h2>{group.name}</h2><p>{group.members.length} membros</p><div className="group-member-list">{group.members.map(member=><div key={member.id}><Avatar user={member} small/><span><StyledName user={member}/><small>@{member.username}</small></span></div>)}</div><button className="prompt-confirm" onClick={startGroupCall}><Phone size={17}/>Iniciar chamada em grupo</button></aside></section>;
}
