import React,{useState,useRef,useEffect} from "react";
import {X,Camera,ImagePlus,Search,Sparkles,Gamepad2,UserRound,ShieldCheck,Check} from "lucide-react";
import {PROFILE_EFFECTS,AVATAR_FRAMES,NAME_EFFECTS,PROFILE_OVERLAYS} from "../cosmetics";
import {premiumCosmetic} from "./premiumCosmetics";
import ProfileOverlay from "./ProfileOverlay";
import {GAME_CATALOG} from "../game-catalog";
import {GameIcon,StyledName} from "./ProfileIdentity";
import ProfileCard from "./ProfileCard";
import {BANNER_PRESETS,PROFILE_THEMES,profilePresentation} from "./profilePresentation";
import useFileDrop from "./useFileDrop";
export {GameIcon,StyledName} from "./ProfileIdentity";
export default function ProfileEditor({user,onClose,onSave,Avatar,ProfileEffectLayer,renderBadges}) {
 const [form,setForm]=useState(()=>({...user,bio:user.bio||"",banner:user.banner||null,avatar:user.avatar||null,
  gameInterests:user.gameInterests||[],password:""}));
 const initial=useRef(JSON.stringify(form));
 const [tab,setTab]=useState("profile"),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[error,setError]=useState("");
 const avatarInput=useRef(null),bannerInput=useRef(null);
 const dropImage=(key,files)=>{if(busy||reading||!files.length)return;if(files.length>1)return setError("Solte uma imagem de cada vez.");imageFile(key,{target:{files,value:""}});};
 const avatarDrop=useFileDrop(files=>dropImage("avatar",files));
 const bannerDrop=useFileDrop(files=>dropImage("banner",files));
 const changed=JSON.stringify(form)!==initial.current;
 useEffect(()=>{const close=event=>{if(event.key==="Escape")onClose();};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[onClose]);
 const nitro=(user.badges||[]).includes("nitro_classic");
 const update=(key,value)=>setForm(current=>({...current,[key]:value}));
 async function save(){
  if(busy||reading)return;setBusy(true);setError("");
  try{await onSave(form);initial.current=JSON.stringify(form);}catch(e){setError(e.message);}finally{setBusy(false);}
 }
 async function imageFile(key,event){
  const file=event.target.files?.[0];event.target.value="";if(!file)return;setError("");
  const head=new Uint8Array(await file.slice(0,12).arrayBuffer());
  const signature=String.fromCharCode(...head);
  const mime=signature.startsWith("GIF87a")||signature.startsWith("GIF89a")?"image/gif":head[0]===137&&head[1]===80?"image/png":head[0]===255&&head[1]===216?"image/jpeg":signature.startsWith("RIFF")&&signature.slice(8)==="WEBP"?"image/webp":null;
  if(!mime)return setError("Use uma imagem PNG, JPEG, WebP ou GIF válida.");
  if(mime==="image/gif"&&!nitro)return setError("Seu perfil precisa da insígnia Nitro Classic para usar GIF. Imagens estáticas estão liberadas.");
  if(file.size>20*1024*1024)return setError("Escolha uma imagem de até 20 MB.");
  setReading(true);
  try{
   let result=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Não foi possível ler a imagem."));reader.readAsDataURL(new Blob([file],{type:mime}));});
   if(result.length>4_000_000){
    if(mime==="image/gif")throw new Error("O GIF ultrapassa o limite de 3 MB. Use um arquivo menor para manter a animação.");
    result=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const canvas=document.createElement("canvas");const scale=Math.min(1,(key==="avatar"?768:1600)/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/webp",.85));};image.onerror=()=>reject(new Error("Imagem inválida."));image.src=result;});
   }
   if(result.length>4_250_000)throw new Error("A imagem ainda é grande demais. Escolha uma menor.");
   update(key,result);
  }catch(e){setError(e.message);}finally{setReading(false);}
 }
 const choices=(field,options)=><div className="studio-grid">{options.map(([value,label])=>{const locked=premiumCosmetic(field,value)&&!nitro;return <button type="button" key={value} disabled={locked} title={locked?"Requer insígnia Nitro Classic":label} className={"studio-choice "+(form[field]===value?"selected ":"")+(locked?"premium-locked":"")} aria-pressed={form[field]===value} onClick={()=>!locked&&update(field,value)}>
  <span className="studio-choice-art">{field==="avatarFrame"?<Avatar user={{...form,avatarFrame:value,cosmeticStatic:true}}/>:field==="nameEffect"?<StyledName user={{...form,nameEffect:value}}>Sesh</StyledName>:<><span className="studio-mini-orb"/>{field==="profileOverlay"?<ProfileOverlay effect={value} animated={false}/>:<ProfileEffectLayer effect={value}/>}</>}</span><span>{label}</span>{locked?<b className="premium-lock">NITRO</b>:form[field]===value&&<Check size={14}/>}</button>})}</div>;
 return <div className="profile-settings-backdrop"><section className="profile-editor" role="dialog" aria-modal="true" aria-label="Editar perfil">
  <aside className="profile-editor-nav"><div className="settings-person"><Avatar user={{...form,cosmeticStatic:true}}/><div><strong>{user.displayName}</strong><small>Seu espaço no Sesh</small></div></div><span className="eyebrow">PERFIL PRINCIPAL</span>
  {[["profile","Perfil",UserRound],["appearance","Efeitos e estilo",Sparkles],["games","Jogos de interesse",Gamepad2],["account","Conta",ShieldCheck]].map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}
  <p>Suas alterações aparecem na prévia. Salve quando estiver tudo pronto.</p></aside>
  <main className="profile-editor-main"><header><div><span className="eyebrow">FAÇA DO SEU JEITO</span><h1>{tab==="profile"?"Um perfil com a sua cara":tab==="appearance"?"Seu estilo, em movimento":tab==="games"?"O que você joga?":"Informações da conta"}</h1></div><button className="settings-close" aria-label="Fechar perfil" onClick={onClose}><X/></button></header>
  <div className="profile-editor-columns"><fieldset className="profile-editor-fields" disabled={busy||reading}>
  {tab==="profile"&&<><section className="settings-card"><h2>Foto e banner</h2><p>Imagens estáticas para todos. GIF animado para contas com a insígnia Nitro Classic.</p><div className="profile-upload-actions"><button type="button" {...avatarDrop.bind} data-drop-target="avatar" className={"secondary-setting image-drop-target"+(avatarDrop.dragging?" dragging":"")} onClick={()=>avatarInput.current.click()}><Camera size={18}/>Alterar foto</button><button type="button" {...bannerDrop.bind} data-drop-target="banner" className={"secondary-setting image-drop-target"+(bannerDrop.dragging?" dragging":"")} onClick={()=>bannerInput.current.click()}><ImagePlus size={18}/>Alterar banner</button></div>
  <input ref={avatarInput} type="file" accept=".png,.jpg,.jpeg,.webp,.gif,image/png,image/jpeg,image/webp,image/gif" hidden onChange={e=>imageFile("avatar",e)}/><input ref={bannerInput} type="file" accept=".png,.jpg,.jpeg,.webp,.gif,image/png,image/jpeg,image/webp,image/gif" hidden onChange={e=>imageFile("banner",e)}/>
  <div className="profile-upload-actions">{form.avatar&&<button className="text-button" onClick={()=>update("avatar",null)}>Remover foto</button>}{form.banner&&<button className="text-button" onClick={()=>update("banner",null)}>Remover banner</button>}</div>
  <p className="upload-hint">GIF animado: até 3 MB, sem converter a animação. PNG, JPEG e WebP: até 20 MB, com otimização.</p>
  <p className="upload-hint">Arraste a imagem para “Alterar foto” ou “Alterar banner”, ou clique para escolher.</p>
  <h3>Fundos prontos</h3><div className="banner-presets">{BANNER_PRESETS.map(([id,label,background])=>{const locked=premiumCosmetic("bannerPreset",id)&&!nitro;return <button type="button" key={id} disabled={locked} title={locked?label+" · Nitro":label} aria-label={"Banner "+label+(locked?" · requer Nitro":"")} aria-pressed={!form.banner&&(form.bannerPreset||"aurora")===id} className={locked?"premium-locked":""} style={{background}} onClick={()=>!locked&&setForm(current=>({...current,banner:null,bannerPreset:id}))}>{locked&&<span>NITRO</span>}</button>})}</div>
  {form.banner?.startsWith("data:image/")&&<div className="banner-position"><h3>Enquadrar banner</h3>{[["X","Horizontal"],["Y","Vertical"]].map(([axis,label])=><label key={axis}>{label}<input type="range" min="0" max="100" aria-label={"Posição "+label.toLowerCase()+" do banner"} value={form["bannerPosition"+axis]??50} onChange={e=>update("bannerPosition"+axis,Number(e.target.value))}/></label>)}<button type="button" className="text-button" onClick={()=>setForm(current=>({...current,bannerPositionX:50,bannerPositionY:50}))}>Centralizar</button></div>}
  </section>
  <section className="settings-card"><label className="setting-field">Nome de exibição<input maxLength={80} value={form.displayName||""} onChange={e=>update("displayName",e.target.value)}/></label><label className="setting-field">Sobre você<textarea maxLength={300} rows={4} placeholder="Conte um pouco sobre você…" value={form.bio} onChange={e=>update("bio",e.target.value)}/><small>{form.bio.length}/300</small></label><label className="setting-field">Atividade<input maxLength={120} placeholder="Preparando a próxima partida" value={form.activityText||""} onChange={e=>update("activityText",e.target.value)}/></label></section></>}
  {tab==="appearance"&&<><section className="settings-card"><h2>Sobreposições do perfil</h2><p>Decorações por cima do cartão, como na referência. Combine com partículas, molduras e suas cores.</p><div style={profilePresentation(form)}>{choices("profileOverlay",PROFILE_OVERLAYS)}</div></section><section className="settings-card"><h2>Molduras de avatar</h2><p>Detalhes que acompanham você no chat e nas chamadas.</p>{choices("avatarFrame",AVATAR_FRAMES)}</section><section className="settings-card"><h2>Efeitos de perfil</h2>{choices("profileEffect",PROFILE_EFFECTS)}<div className="effect-controls"><label className="setting-field">Intensidade<select value={form.effectIntensity||"balanced"} onChange={e=>update("effectIntensity",e.target.value)}><option value="subtle">Suave</option><option value="balanced">Equilibrada</option><option value="vivid">Intensa</option></select></label><label className="setting-field">Velocidade<select value={form.effectSpeed||"normal"} onChange={e=>update("effectSpeed",e.target.value)}><option value="slow">Lenta</option><option value="normal">Normal</option><option value="fast">Rápida</option></select></label></div><h3>Cores do perfil</h3><div className="effect-controls"><label className="setting-field">Cor de fundo<input type="color" value={form.profilePrimaryColor||"#191923"} onChange={e=>update("profilePrimaryColor",e.target.value)}/></label><label className="setting-field">Cor de destaque<input type="color" value={form.profileAccentColor||"#9485fa"} onChange={e=>update("profileAccentColor",e.target.value)}/></label></div><button type="button" className="text-button" onClick={()=>setForm(current=>({...current,profilePrimaryColor:null,profileAccentColor:null}))}>Usar cores do tema</button><div className="profile-theme-choices">{PROFILE_THEMES.map(([id,label,color])=><button type="button" key={id} aria-pressed={(form.profileTheme||"default")===id} onClick={()=>setForm(current=>({...current,profileTheme:id,profilePrimaryColor:null,profileAccentColor:null}))}><i style={{background:color}}/>{label}</button>)}</div></section><section className="settings-card"><h2>Estilo do nome</h2>{choices("nameEffect",NAME_EFFECTS)}<label className="setting-field">Cor principal<input type="color" value={form.nameColor||"#f1f3f5"} onChange={e=>update("nameColor",e.target.value)}/></label><label className="setting-field">Fonte<select value={form.nameStyle||"default"} onChange={e=>update("nameStyle",e.target.value)}>{["default","serif","rounded","mono","pixel","script","gothic"].map(font=><option key={font} value={font}>{font==="default"?"Padrão":font}</option>)}</select></label></section></>}
  {tab==="games"&&<section className="settings-card"><h2>Seus jogos favoritos <small>{form.gameInterests.length}/12</small></h2><p>Selecione até 12 jogos. O primeiro aparece em destaque no seu perfil. Clique em um jogo selecionado abaixo para destacá-lo e salve as alterações.</p><div className="selected-games">{form.gameInterests.map(id=>GAME_CATALOG.find(game=>game.id===id)).filter(Boolean).map((game,index)=><button type="button" key={game.id} aria-label={"Destacar "+game.name} aria-pressed={index===0} onClick={()=>update("gameInterests",[game.id,...form.gameInterests.filter(id=>id!==game.id)])}><GameIcon game={game}/>{game.name}{index===0&&<span>Favorito</span>}</button>)}</div><label className="settings-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar entre 400 jogos"/></label><div className="games-gallery">{GAME_CATALOG.filter(game=>game.name.toLowerCase().includes(query.toLowerCase())).map(game=><button className={form.gameInterests.includes(game.id)?"selected":""} key={game.id} disabled={!form.gameInterests.includes(game.id)&&form.gameInterests.length>=12} onClick={()=>update("gameInterests",form.gameInterests.includes(game.id)?form.gameInterests.filter(id=>id!==game.id):[...form.gameInterests,game.id])}><GameIcon game={game}/><span>{game.name}</span>{form.gameInterests.includes(game.id)&&<Check size={14}/>}</button>)}</div><label className="setting-field">Lista de desejos<textarea maxLength={300} value={form.wishlist||""} onChange={e=>update("wishlist",e.target.value)}/></label></section>}
  {tab==="account"&&<section className="settings-card"><h2>Dados da conta</h2><label className="setting-field">Nome de usuário<input minLength={user.canUseShortUsername?1:4} maxLength={20} value={form.username||""} onChange={e=>update("username",e.target.value)}/><small>O @ é único. Contas comuns usam no mínimo 4 caracteres.</small></label><label className="setting-field">ID público<input readOnly value={user.publicId||"Gerado ao salvar"} onFocus={event=>event.target.select()}/><small>Seu ID não muda e pode ser usado para identificar a conta.</small></label><label className="setting-field">E-mail<input type="email" value={form.email||""} onChange={e=>update("email",e.target.value)} disabled={user.isMasterAdmin||user.isCreator}/></label><label className="setting-field">Nova senha<input type="password" autoComplete="new-password" value={form.password} onChange={e=>update("password",e.target.value)}/><small>Deixe vazio para manter sua senha atual.</small></label></section>}
  </fieldset><aside className="profile-editor-preview"><span className="eyebrow">PRÉVIA AO VIVO</span><ProfileCard user={form} Avatar={Avatar} ProfileEffectLayer={ProfileEffectLayer} renderBadges={renderBadges} presence={user.status||"online"}/><p>O mesmo cartão, enquadramento e efeitos que as outras pessoas veem.</p></aside></div>
  </main><footer className="profile-save-bar"><div role="status">{error?<span className="save-error">{error}</span>:reading?"Preparando imagem…":changed?"Você tem alterações não salvas.":"Tudo salvo. Pronto para conversar."}</div><button className="prompt-confirm" disabled={busy||reading} onClick={save}>{busy?"Salvando…":"Salvar alterações"}</button></footer>
 </section></div>;
}
